name: On Push

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    uses: BuilderHub/actions/.github/workflows/buildah-build-push-workflow.yaml@v0.1.0-beta.2
    with:
      image: build-api
      tags: "latest ${{ github.sha }}"
      containerfiles: Dockerfile
      context: .
      registry: ghcr.io/builderhub
      push: ${{ github.event_name == 'push' }}
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
